
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('posts').del()
    .then(function () {
      // Inserts seed entries
      return knex('posts').insert([
        {user_id: 2, title: "Look at my cool project", content: "Here is my cool project.", upvote: 0, downvote: 0, type_id: 2},
        {user_id: 2, title: "onClick", content: "Trying to get on click to work. It's a challenge.", upvote: 1, downvote: 0, type_id: 5},
        {user_id: 2, title: "Styling", content: "Trying to do cool styling like I saw on this site. It's a challenge.", upvote: 1, downvote: 0, type_id: 3},
        {user_id: 2, title: "Accumulator", content: "Check out the accumulator I built.", upvote: 1, downvote: 0, type_id: 4},
        {user_id: 3, title: "Machine Learning", content: "Trying to figure out the python I need to use this machine learning project.", upvote: 1, downvote: 0, type_id: 17},
        {user_id: 1, title: "Grabbing elements", content: "Having trouble grabbing these elements. Please help.", upvote: 1, downvote: 0, type_id: 5},
        {user_id: 3, title: "Look at this Ajax problem I'm having", content: "Here is my cool project, but Im still having this problem.", upvote: 0, downvote: 0, type_id: 6},
        {user_id: 1, title: "Node issue", content: "Can you help me with this node issue?", upvote: 1, downvote: 0, type_id: 7},
        {user_id: 2, title: "Installing express", content: "Do I do npm install express --save or do I not need the --save?", upvote: 1, downvote: 0, type_id: 8},
        {user_id: 3, title: "React", content: "Check out the stuff I built.", upvote: 1, downvote: 0, type_id: 10},
        {user_id: 2, title: "Redux problem - need help", content: "Trying to do cool stuff like I saw on this site. It's a challenge.", upvote: 1, downvote: 0, type_id: 11},
        {user_id: 3, title: "Angular is giving me issues", content: "Can you take a look at this and explain why its not working?", upvote: 1, downvote: 0, type_id: 12},
        {user_id: 3, title: "Knex problems", content: "Can you take a look at this and explain why its not working?", upvote: 1, downvote: 0, type_id: 9},
        {user_id: 2, title: "Should I use Vue for this?", content: "Is this  a project I should be using chrome for?", upvote: 1, downvote: 0, type_id: 13},
        {user_id: 1, title: "New to Java", content: "Can you help me out with this?", upvote: 1, downvote: 0, type_id: 14},
        {user_id: 3, title: "Look at this cool stuff", content: "Look at this cool stuff you can use C# for!", upvote: 1, downvote: 0, type_id: 15},
        {user_id: 3, title: "Having a .Net issue", content: "Can you take a look at this and explain why its not working?", upvote: 1, downvote: 0, type_id: 16},
        {user_id: 1, title: "Can you do this in Django?", content: "Can you take a look at this and explain why its not working?", upvote: 1, downvote: 0, type_id: 18},
        {user_id: 2, title: "New to computer science", content: "Can you take a look at this and explain why its not working?", upvote: 1, downvote: 0, type_id: 19},
        {user_id: 2, title: "Check out this project", content: "Here is my cool project.", upvote: 0, downvote: 0, type_id: 2},
        {user_id: 2, title: "DOM idea", content: "Trying to get on click to work. It's a challenge.", upvote: 1, downvote: 0, type_id: 5},
        {user_id: 2, title: "CSS tricks", content: "Trying to do cool styling like I saw on this site. It's a challenge.", upvote: 1, downvote: 0, type_id: 3},
        {user_id: 2, title: "JS arrays?", content: "Check out the accumulator I built.", upvote: 1, downvote: 0, type_id: 4},
        {user_id: 3, title: "use python for this?", content: "Trying to figure out the python I need to use this machine learning project.", upvote: 1, downvote: 0, type_id: 17},
        {user_id: 1, title: "using elements", content: "Having trouble grabbing these elements. Please help.", upvote: 1, downvote: 0, type_id: 5},
        {user_id: 3, title: "Look at this problem I'm having", content: "Here is my cool project, but Im still having this problem.", upvote: 0, downvote: 0, type_id: 6},
        {user_id: 1, title: "Node?", content: "Can you help me with this node issue?", upvote: 1, downvote: 0, type_id: 7},
        {user_id: 2, title: "Using express", content: "Do I use express for this?", upvote: 1, downvote: 0, type_id: 8},
        {user_id: 3, title: "React is giving me this error", content: "Check out the stuff I built.", upvote: 1, downvote: 0, type_id: 10},
        {user_id: 2, title: "Redux problems", content: "Trying to do cool stuff like I saw on this site. It's a challenge.", upvote: 1, downvote: 0, type_id: 11},
        {user_id: 3, title: "Angular is new to me", content: "Can you take a look at this and explain why its not working?", upvote: 1, downvote: 0, type_id: 12},
        {user_id: 3, title: "Knex, knex, knex", content: "Can you take a look at this and explain why its not working?", upvote: 1, downvote: 0, type_id: 9},
        {user_id: 2, title: "Vue is giving me trouble", content: "Is this  a project I should be using chrome for?", upvote: 1, downvote: 0, type_id: 13},
        {user_id: 1, title: "New Java problem", content: "Can you help me out with this?", upvote: 1, downvote: 0, type_id: 14},
        {user_id: 3, title: "Look at this nifty stuff", content: "Look at this cool stuff you can use C# for!", upvote: 1, downvote: 0, type_id: 15},
        {user_id: 3, title: "Having a problem", content: "Can you take a look at this and explain why its not working?", upvote: 1, downvote: 0, type_id: 16},
        {user_id: 1, title: "Can you help me with Django?", content: "Can you take a look at this and explain why its not working?", upvote: 1, downvote: 0, type_id: 18},
        {user_id: 2, title: "computer science stuff", content: "Can you take a look at this and explain why its not working? What am I doing wrong?", upvote: 1, downvote: 0, type_id: 19},
        {user_id: 2, title: "Look at this problem", content: "Here is my cool project but here is this problem.", upvote: 0, downvote: 0, type_id: 2},
        {user_id: 2, title: "Jquery problem", content: "Trying to get this to work. It's a challenge.", upvote: 1, downvote: 0, type_id: 5},
        {user_id: 2, title: "Styling", content: "Check out this new styling stuff I just learned", upvote: 1, downvote: 0, type_id: 3},
        {user_id: 2, title: "JS objects", content: "Check out the object I'm working with.", upvote: 1, downvote: 0, type_id: 4},
        {user_id: 3, title: "Python stuff", content: "Trying to figure out the python I need to use this machine learning project.", upvote: 1, downvote: 0, type_id: 17},
        {user_id: 1, title: "Manipulating elements", content: "Having trouble grabbing these elements. Please help.", upvote: 1, downvote: 0, type_id: 5},
        {user_id: 3, title: "Look at this Ajax problem I solved", content: "Here is my cool project, but Im still having this problem.", upvote: 0, downvote: 0, type_id: 6},
        {user_id: 1, title: "Node stuff is handy", content: "Can you help me with this node issue?", upvote: 1, downvote: 0, type_id: 7},
        {user_id: 2, title: "My express problem", content: "Do I do npm install express --save or do I not need the --save?", upvote: 1, downvote: 0, type_id: 8},
        {user_id: 3, title: "React stuff", content: "Check out the stuff I built.", upvote: 1, downvote: 0, type_id: 10},
        {user_id: 2, title: "Redux problem - SOS!", content: "Trying to do cool stuff like I saw on this site. It's a challenge.", upvote: 1, downvote: 0, type_id: 11},
        {user_id: 3, title: "Angular is giving a problem too", content: "Can you take a look at this and explain why its not working?", upvote: 1, downvote: 0, type_id: 12},
        {user_id: 3, title: "Knex issues", content: "Can you take a look at this and explain why its not working?", upvote: 1, downvote: 0, type_id: 9},
        {user_id: 2, title: "Can I use Vue for this?", content: "Is this  a project I should be using chrome for?", upvote: 1, downvote: 0, type_id: 13},
        {user_id: 1, title: "New to Java - what's this about?", content: "Can you help me out with this?", upvote: 1, downvote: 0, type_id: 14},
        {user_id: 3, title: "Look at this awsome stuff", content: "Look at this cool stuff you can use C# for!", upvote: 1, downvote: 0, type_id: 15},
        {user_id: 3, title: "Having a .Net issue", content: "Can you take a look at this and explain why its not working?", upvote: 1, downvote: 0, type_id: 16},
        {user_id: 1, title: "Django can be used for this problem??", content: "Can you take a look at this and explain why its not working?", upvote: 1, downvote: 0, type_id: 18},
        {user_id: 2, title: "WAT?????", content: "Can you take a look at this and explain why its not working?", upvote: 1, downvote: 0, type_id: 19},
        {user_id: 1, title: "Look how interesting this is!!!", content: "Can you take a look at this? How interesting, right???", upvote: 1, downvote: 0, type_id: 1},
        {user_id: 2, title: "WAT?????", content: "How cool!!", upvote: 1, downvote: 0, type_id: 1},
        {user_id: 3, title: "Interesting", content: "This is super interesting!!", upvote: 1, downvote: 0, type_id: 1},
        {user_id: 3, title: "Check this out!", content: "This is super interesting!!", upvote: 1, downvote: 0, type_id: 1},

      ]);
    });
};
